In [1]:
import numpy as np

In [2]:
np.__version__


'1.19.5'

# Creating Array

**1) Creating from other structure**

In [3]:
arr=np.array([1,2,3,4])

In [4]:
print(arr,type(arr))

[1 2 3 4] <class 'numpy.ndarray'>


In [5]:
arr=np.array([[1,2,3,4]])
print(arr,type(arr))

[[1 2 3 4]] <class 'numpy.ndarray'>


In [6]:
l=[1,2,3,4,5]
print(l)

[1, 2, 3, 4, 5]


In [7]:
arr=np.array(l)
print(arr,type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [8]:
#Set Array
arr=np.array({1,2,3,4,5,4,6})
print(arr)


{1, 2, 3, 4, 5, 6}


In [9]:
#Dictionary Array

arr=np.array({1:'a',2:'b',3:'c'})
print(arr)

{1: 'a', 2: 'b', 3: 'c'}


In [10]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
arr.dtype

dtype('int32')

In [12]:
arr.shape

(3, 3)

In [13]:
arr.size

9

**We can also do the memory management as in python there is no pointer so we use numpy for this**


In [14]:
arr=np.array([3,4,5,6],np.int32)
print(arr)

[3 4 5 6]


# Creating array from functions

**Zero Array**

In [15]:
arr=np.zeros([2,2])
print(arr)

[[0. 0.]
 [0. 0.]]


**Arange Method**

arange(startrange, endrange+1, distance)


In [16]:
arr=np.arange(1,10,1)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [17]:
arr=np.arange(10,1,-1)
print(arr)

[10  9  8  7  6  5  4  3  2]


In [18]:
arr=np.arange(1,10,1)
arr=arr.reshape(3,3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


**linspace()**
kisi range k according equally divide no
like 1-4 with 4 element 

In [19]:
arr=np.linspace(1,4,4)
print(arr)

[1. 2. 3. 4.]


In [20]:
arr=np.linspace(1,4,8)
print(arr)

[1.         1.42857143 1.85714286 2.28571429 2.71428571 3.14285714
 3.57142857 4.        ]


In [21]:
arr=np.linspace(1,10,23)
print(arr)

[ 1.          1.40909091  1.81818182  2.22727273  2.63636364  3.04545455
  3.45454545  3.86363636  4.27272727  4.68181818  5.09090909  5.5
  5.90909091  6.31818182  6.72727273  7.13636364  7.54545455  7.95454545
  8.36363636  8.77272727  9.18181818  9.59090909 10.        ]


**empty array** will give you a array as per the shape that was given by you with randoms no

In [22]:
emp=np.empty((3,3))
print(emp)

[[0.00e+000 0.00e+000 0.00e+000]
 [0.00e+000 0.00e+000 5.77e-321]
 [0.00e+000 0.00e+000 0.00e+000]]


**Identity array**

In [23]:
arr=np.identity(2)
print(arr)

[[1. 0.]
 [0. 1.]]


**Now reshaping an array**

In [24]:
arr=np.arange(1,100,1)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [25]:
arr=arr.reshape(3,33)
print(arr)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
  25 26 27 28 29 30 31 32 33]
 [34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
  58 59 60 61 62 63 64 65 66]
 [67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90
  91 92 93 94 95 96 97 98 99]]


**ravel** for creating 1 d array

In [26]:
arr=arr.ravel()
print(arr, arr.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99] (99,)


**Now working on axis** 0 -> row     and 1-> column

In [27]:
x=[[1,2,3],[4,5,6],[7,1,0]]
arr=np.array(x)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 1 0]]


In [28]:
arr.sum(axis=0)

array([12,  8,  9])

In [29]:
arr.sum(axis=1)

array([ 6, 15,  8])

**Numpy functions and attribute**

***Transpose***

In [30]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [31]:
arr.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [32]:
#storing in a list

arr.flat

In [33]:
for i in arr.flat:
    print(i)

1
2
3
4
5
6
7
1
0


In [34]:
#ndim = gives you dimension

arr.ndim

2

In [35]:
#For size = 9 element h
arr.size

9

In [36]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [37]:
arr.nbytes

36

In [38]:
arr=np.array([1,2,3,54,6,2,0])

In [39]:
#print the index of greater number
arr.argmax()

3

In [40]:
arr.argmin()


6

In [41]:
#Sort by index

arr.argsort()

array([6, 0, 1, 5, 2, 4, 3], dtype=int64)

**Now with 2-D array**

In [42]:
arr=np.array([[1,2,3],[4,5,6],[7,1,0]])

In [43]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [44]:
arr.argmax()

6

In [45]:
arr.argmin()

8

In [46]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [47]:
#0-> row
#1->column


arr.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [48]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [49]:
arr.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [50]:
arr.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [51]:
#1 D array
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [52]:
arr.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [53]:
arr2=np.arange(1,10,1).reshape(3,3)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
arr+arr2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14,  9,  9]])

In [55]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [56]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
arr+arr2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14,  9,  9]])

In [58]:
arr*arr2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49,  8,  0]])

In [59]:
arr.dot(arr2)

array([[30, 36, 42],
       [66, 81, 96],
       [11, 19, 27]])

In [60]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [61]:
arr.sum()

29

In [62]:
arr.min()

0

In [63]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [64]:
#where element are exist
print(np.where(arr>5))


(array([1, 2], dtype=int64), array([2, 0], dtype=int64))


In [65]:
#Memory diff
import sys

In [66]:
py_ar=[1,2,3,4,5]
sys.getsizeof(1)*len(py_ar)


140

In [67]:
np_ar=np.array(py_ar)
np_ar.itemsize*np_ar.size


20

In [68]:
#numpy arr ki python list

arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [69]:
y = np.array([3+4j, 0.4+7.8j])
print(y.dtype)

complex128


In [70]:
x = np.array([[3.2, 7.8, 9.2],
             [4.5, 9.1, 1.2]], dtype='int64')
print(x.itemsize)

8


In [71]:
n = [5, 10, 15, 20, 25]
x=np.array(n)
print(type(x))


<class 'numpy.ndarray'>


In [72]:
x.shape


(5,)

In [73]:
x.ndim

1

In [74]:
x.size

5

In [75]:
n = [[-1, -2, -3, -4], [-2,-4, -6, -8]]
y=np.array(n)

In [76]:
type(y)

numpy.ndarray

In [77]:
print(y.ndim)

2


In [78]:
print(y.shape)

(2, 4)


In [79]:
print(y.size)

8


In [80]:
print(y.itemsize)

4


In [81]:
print(y.nbytes)

32


**ndarry from Lists**

In [82]:
a=[[[4.1,2.5],[1.1,2.3],[9.1,2.5]],[[8.6,9.9],[3.6,4.3],[6.6,0.3]]]
x=np.array(a,dtype='float64')
x

array([[[4.1, 2.5],
        [1.1, 2.3],
        [9.1, 2.5]],

       [[8.6, 9.9],
        [3.6, 4.3],
        [6.6, 0.3]]])

In [83]:
type(x),x.ndim,x.shape

(numpy.ndarray, 3, (2, 3, 2))

**Using zeros method**

In [84]:
x=np.zeros(shape=(2,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

 **Using full method**

In [85]:
x=np.full(shape=(2,4),fill_value=0.5)
x

array([[0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5]])

**arange : Numbers created based on step value.**
    Syntax - numpy.arange([start, ]stop, [step, ]dtype=None)



In [86]:
x=np.arange(3,15,2.5)
x

array([ 3. ,  5.5,  8. , 10.5, 13. ])

**linspace : Numbers created based on size value.**
    Syntax - numpy.linspace(start, stop, #num inbetween, endpoint=True, retstep=False, dtype=None)

In [87]:
x=np.arange(3,15,3)
x


array([ 3,  6,  9, 12])

**Random Numbers Generator**
random module of numpy is used to generate various random sequences.


In [88]:
x=np.random.rand(2,2)
x

array([[0.83133736, 0.25014927],
       [0.55869495, 0.62200609]])

In [89]:
y=np.random.randint(10,50,3)
y

array([15, 43, 23])

# Reading Data from a file


In [90]:
from io import StringIO
x = StringIO('''88.25 93.45 72.60 90.90
72.3 78.85 92.15 65.75
90.5 92.45 89.25 94.50
''')


In [91]:
d=np.loadtxt(x,delimiter=' ')
d

array([[88.25, 93.45, 72.6 , 90.9 ],
       [72.3 , 78.85, 92.15, 65.75],
       [90.5 , 92.45, 89.25, 94.5 ]])

In [92]:
print(d.ndim,d.shape)

2 (3, 4)


In [93]:
np.random.rand(3, 2)

array([[0.7507134 , 0.27252235],
       [0.94471968, 0.77443485],
       [0.80976681, 0.69963954]])

In [94]:
x1=np.array([[[-1,1],[-2,2]],[[-3, 3], [-4, 4]]])

In [95]:
x1.ndim

3

In [96]:
x1.shape

(2, 2, 2)

In [97]:
x1.size

8

In [98]:

x=np.full(shape=(3,2,2),fill_value=1)
x

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [99]:
x3=np.identity(3)
x3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Reshaping the array**

In [100]:
x=np.random.randint(10,500,8)
x

array([ 21,  26, 281,  63,  66, 108, 366, 342])

In [101]:
print(x, end='\n\n')

[ 21  26 281  63  66 108 366 342]



In [102]:
y=x.reshape(2,4)
y

array([[ 21,  26, 281,  63],
       [ 66, 108, 366, 342]])

In [103]:
print(y, end='\n\n')

[[ 21  26 281  63]
 [ 66 108 366 342]]



In [104]:
z = x.reshape(2,2,2)
z

array([[[ 21,  26],
        [281,  63]],

       [[ 66, 108],
        [366, 342]]])

**Stacking arrays vertically**   
Two or more arrays can be joined vertically using the generic vstack method.

In [105]:
x = np.array([[-1, 1], [-3, 3]])
y = np.array([[-2, 2], [-4, 4]])

In [106]:
np.vstack((x,y))

array([[-1,  1],
       [-3,  3],
       [-2,  2],
       [-4,  4]])

**Stacking arrays horizontally**
Two or more arrays can be joined horizontally using the generic **hstack** method.


In [107]:
x = np.array([[-1, 1], [-3, 3]])
y = np.array([[-2, 2], [-4, 4]])
z = np.array([[-5, 5], [-6, 6]])
np.hstack((x,y,z))

array([[-1,  1, -2,  2, -5,  5],
       [-3,  3, -4,  4, -6,  6]])

**Splitting arrays vertically**
Arrays can be split vertically using the generic vsplit method.


In [108]:
x = np.arange(30).reshape(6, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [109]:
res=np.vsplit(x,2)
res

[array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]])]

In [110]:
print(res[0], end='\n\n')
print(res[1])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[[15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


***It is also possible to split at specific row numbers using vsplit.***

In [111]:
x = np.arange(30).reshape(6, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [112]:
res=np.vsplit(x,(2,5))
res

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]),
 array([[25, 26, 27, 28, 29]])]

**Splitting arrays Horizontally** Arrays can be split horizontally using the generic hsplit method.


In [113]:
x = np.arange(10).reshape(2, 5)
res=np.hsplit(x,(2,4))
res 

[array([[0, 1],
        [5, 6]]),
 array([[2, 3],
        [7, 8]]),
 array([[4],
        [9]])]

In [114]:
x=np.arange(1,21,1)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [115]:
z=x.reshape(4,5)
z

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [117]:
p=np.array([3,6,9,12]).reshape(2,2)
q=np.array([15, 18, 21, 24, 27, 30]).reshape(2,3)
p,q

(array([[ 3,  6],
        [ 9, 12]]),
 array([[15, 18, 21],
        [24, 27, 30]]))

In [118]:
np.hstack((p,q))

array([[ 3,  6, 15, 18, 21],
       [ 9, 12, 24, 27, 30]])

In [119]:
x = np.arange(20).reshape(4,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [120]:
print(x.mean(axis=1))

[ 2.  7. 12. 17.]


In [121]:
x = np.array([[-2], 
              [2]])
y = np.array([[-3, 3]])
print(x + y)

[[-5  1]
 [-1  5]]


# Indexing, Slicing a 1-D ndarray


In [123]:
#Slicing refers to extracting a portion of existing array.
#This can be achieved with a slice object.
#A slice object is of the form start:end:step. All three are optional.
#Having only a single number inside square brackets refer to start index.
